-- catalog-version: sha256:78938910caaacb61310772c5559ebb36119463f01194f472ed220f9762d70ad5
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p2-0117-hanover-insurance', 2632, 'Hanover Insurance', 'https://jobs.dayforcehcm.com/en-US/thg/ALLCAREERS', 'https://www.hanover.com/careers', '공식 Career Portal', 'custom', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-14') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-1082-trinetx', 2759, 'TriNetX', 'https://jobs.dayforcehcm.com/en-US/trinetx1/CANDIDATEPORTAL', 'https://trinetx.com/careers/', '공식 Career Portal', 'custom', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-14') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('legacy-row-787', 2787, 'Asbury Automotive Group', 'https://jobs.dayforcehcm.com/en-US/asburyauto/ASBURYCAREERSITE', 'https://www.asburycareers.com/', '공식 Career Portal', 'custom', 'career_page_only', 'medium', 'unknown', 'unknown', 1, '2026-08-14') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('legacy-row-826', 2826, 'Interactive Brokers Group', 'https://jobs.dayforcehcm.com/en-US/ibgllc/CANDIDATEPORTAL', 'https://www.interactivebrokers.com/en/general/about/careers.php', '공식 Career Portal', 'custom', 'career_page_only', 'high-medium', 'unknown', 'unknown', 1, '2026-08-14') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p2-0113-golden-1-credit-union', 2914, 'Golden 1 Credit Union', 'https://jobs.dayforcehcm.com/en-US/golden1/CANDIDATEPORTAL', 'https://www.golden1.com/careers', '공식 Career Portal', 'custom', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-14') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-p2-0117-hanover-insurance', 'p2-0117-hanover-insurance', 'https://www.hanover.com/careers', 'unknown', 'unknown', '2026-08-14') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-p5-1082-trinetx', 'p5-1082-trinetx', 'https://trinetx.com/careers/', 'unknown', 'unknown', '2026-08-14') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-legacy-row-787', 'legacy-row-787', 'https://www.asburycareers.com/', 'unknown', 'unknown', '2026-08-14') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-legacy-row-826', 'legacy-row-826', 'https://www.interactivebrokers.com/en/general/about/careers.php', 'unknown', 'unknown', '2026-08-14') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-p2-0113-golden-1-credit-union', 'p2-0113-golden-1-credit-union', 'https://www.golden1.com/careers', 'unknown', 'unknown', '2026-08-14') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;

-- The new Dayforce adapter is live, so release only the five verified sources
-- from their previous failure backoff. The scheduled workflow owns execution.
UPDATE sources
SET next_crawl_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN (
  'p2-0117-hanover-insurance',
  'p5-1082-trinetx',
  'legacy-row-787',
  'legacy-row-826',
  'p2-0113-golden-1-credit-union'
);
