-- catalog-version: sha256:56b14e13f85837175f4da8f04fddc548dedb7821d2683a4aa615ac83bff343e2
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('audit-row-395', 395, 'McDonald''s', 'https://careers.smartrecruiters.com/mcdonaldscorporation', NULL, '공식 채용공고/ATS', 'smartrecruiters', 'career_only', 'medium', 'job_only', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('audit-row-438', 438, 'WESCO International', 'https://careers.smartrecruiters.com/WESCO1', NULL, '공식 채용공고/ATS', 'smartrecruiters', 'career_only', 'medium', 'job_only', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-0533-agilent-technologies', 1452, 'Agilent Technologies', 'https://careers.smartrecruiters.com/AgilentTechnologies2', NULL, '공식 채용 공고/ATS', 'smartrecruiters', 'career_only', 'medium', 'job_only', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('legacy-row-128', 2128, 'Westinghouse Air Brake', 'https://careers.smartrecruiters.com/Wabtec', 'https://careers.wabtec.com/', 'Wabtec Talent Community', 'smartrecruiters', 'valid_embedded_talent_network', 'high', 'unknown', 'available', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-0565-canva', 2362, 'Canva (AI)', 'https://careers.smartrecruiters.com/canva', 'https://www.canva.com/careers/', '공식 채용공고 검색·지원', 'smartrecruiters', 'not_audited', 'medium', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-0803-arista-networks', 2414, 'Arista Networks', 'https://careers.smartrecruiters.com/AristaNetworks', 'https://www.arista.com/en/careers', '공식 채용공고 검색·지원', 'smartrecruiters', 'not_audited', 'medium', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('legacy-row-780', 2780, 'Albertsons', 'https://careers.smartrecruiters.com/AlbertsonsCompanies', 'https://www.albertsonscompanies.com/careers.html', '공식 Career Portal', 'smartrecruiters', 'career_page_only', 'medium', 'unknown', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0298-j-s-held', 2976, 'J.S. Held', 'https://careers.smartrecruiters.com/JSHeldLLC', 'https://www.jsheld.com/about-us/careers', '공식 Career Portal', 'smartrecruiters', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0435-freshworks', 3027, 'Freshworks', 'https://careers.smartrecruiters.com/Freshworks', 'https://www.freshworks.com/careers', '공식 Career Portal', 'smartrecruiters', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0313-nbcuniversal', 3233, 'NBCUniversal', 'https://careers.smartrecruiters.com/NBCUniversal3', 'https://www.nbcunicareers.com/talent-community', 'NBCUniversal Talent Community', 'smartrecruiters', 'valid_direct_talent_form', 'high', 'unknown', 'available', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-0668-microchip-technology', 3419, 'Microchip Technology', 'https://careers.smartrecruiters.com/Microchip', 'https://www.microchip.com/en-us/about/careers', '공식 Career Portal', 'smartrecruiters', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
-- These official SmartRecruiters boards were previously handled by generic
-- HTML discovery and may still be in failure backoff. Make only this verified
-- set eligible for the next server-owned workflow; this does not start a crawl.
UPDATE `sources`
SET `next_crawl_at` = CURRENT_TIMESTAMP,
    `updated_at` = CURRENT_TIMESTAMP
WHERE `id` IN (
  'audit-row-395',
  'audit-row-438',
  'p5-0533-agilent-technologies',
  'legacy-row-128',
  'p5-0565-canva',
  'p5-0803-arista-networks',
  'legacy-row-780',
  'p4-0298-j-s-held',
  'p4-0435-freshworks',
  'p4-0313-nbcuniversal',
  'p5-0668-microchip-technology'
);
