-- catalog-version: sha256:880ba20685d9328bc30189bd4bd7f289d875579fd145ac76998ee3690ab803e5
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-0750-thales-us', 263, 'Thales US (Thales Group)', 'https://thales.wd3.myworkdayjobs.com/Careers', NULL, '공식 채용공고 검색·지원', 'workday', 'career_only', 'medium', 'job_only', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('audit-row-369', 369, 'Hertz Global Holdings', 'https://fa-evlf-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs', NULL, '공식 채용공고/ATS', 'custom', 'career_only', 'medium', 'job_only', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p2-0181-voya-financial', 1288, 'Voya Financial', 'https://godirect.wd5.myworkdayjobs.com/voya_jobs', NULL, '공식 채용 공고/ATS', 'workday', 'career_only', 'medium', 'job_only', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0360-t-rowe-price', 2658, 'T. Rowe Price', 'https://troweprice.wd5.myworkdayjobs.com/TRowePrice', 'https://troweprice.gr8people.com/talent-pools/19307/data-analytics', 'T. Rowe Price Data Analytics Talent Community', 'workday', 'valid_direct_talent_form', 'high', 'unknown', 'available', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-0745-take-two-interactive', 2715, 'Take-Two Interactive', 'https://job-boards.greenhouse.io/taketwo', 'https://careers.take2games.com/', '공식 Career Portal', 'greenhouse', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-1015-pathai', 2735, 'PathAI', 'https://job-boards.greenhouse.io/pathai', 'https://www.pathai.com/careers', 'Career portal only — open positions', 'greenhouse', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-1050-samsung-semiconductor', 2747, 'Samsung Semiconductor', 'https://sec.wd3.myworkdayjobs.com/Samsung_Careers', 'https://semiconductor.samsung.com/sas/work-with-us/job-opportunities/', 'Samsung Austin Semiconductor job-by-job applications', 'workday', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-1107-welldoc', 2770, 'Welldoc', 'https://welldoc.bamboohr.com/careers', 'https://www.welldoc.com/careers/', '공식 Career Portal', 'custom', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p1-0007-kroll', 2889, 'Kroll', 'https://hcxs.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs', 'https://careers.kroll.com/en', 'Career portal only — no public general talent form found', 'custom', 'career_page_only', 'medium-high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p2-0116-hancock-whitney', 2916, 'Hancock Whitney', 'https://hancockwhitney.wd5.myworkdayjobs.com/Careers', 'https://www.hancockwhitney.com/careers', '공식 Career Portal', 'workday', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0334-quantexa', 2990, 'Quantexa', 'https://jobs.ashbyhq.com/quantexa', 'https://www.quantexa.com/careers/', '공식 Career Portal', 'ashby', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0495-securonix', 3045, 'Securonix', 'https://securonix.bamboohr.com/careers', 'https://www.securonix.com/company/careers/', '공식 Career Portal', 'custom', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0506-tiger-analytics', 3048, 'Tiger Analytics', 'https://apply.workable.com/tiger-analytics/', 'https://www.tigeranalytics.com/about-us/current-openings/', '공식 Career Portal', 'custom', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0521-zscaler', 3054, 'Zscaler', 'https://job-boards.greenhouse.io/zscaler', 'https://www.zscaler.com/careers', '현행 공식 Career Portal', 'greenhouse', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0515-wiz', 3328, 'Wiz', 'https://job-boards.greenhouse.io/wizinc', 'https://www.wiz.io/careers', '공식 Career Portal', 'greenhouse', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
-- The old corporate landing pages did not expose stable server-rendered job
-- identities. Requeue only the sources whose first-party ATS catalogs were
-- verified against current official posting URLs in the production database.
UPDATE `sources`
SET `next_crawl_at` = CURRENT_TIMESTAMP,
    `updated_at` = CURRENT_TIMESTAMP
WHERE `id` IN (
  'audit-row-369',
  'p1-0007-kroll',
  'p2-0116-hancock-whitney',
  'p2-0181-voya-financial',
  'p4-0334-quantexa',
  'p4-0360-t-rowe-price',
  'p4-0495-securonix',
  'p4-0506-tiger-analytics',
  'p4-0515-wiz',
  'p4-0521-zscaler',
  'p5-0745-take-two-interactive',
  'p5-0750-thales-us',
  'p5-1015-pathai',
  'p5-1050-samsung-semiconductor',
  'p5-1107-welldoc'
);
