-- catalog-version: sha256:f5203b62e098e218c3586100d554022f7a864f711a4586cb13aee8c85ba85277
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-1041-rippling', 292, 'Rippling', 'https://www.rippling.com/careers/open-roles', NULL, '공식 채용공고 검색·지원', 'custom', 'career_only', 'medium', 'job_only', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('audit-row-342', 342, 'Delta Air Lines', 'https://delta.avature.net/en_US/careers/SearchJobs', NULL, '공식 채용공고 검색·지원', 'custom', 'career_only', 'medium', 'job_only', 'unknown', 1, '2026-08-08') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0450-jfrog', 3032, 'JFrog', 'https://join.jfrog.com/positions', 'https://jfrog.com/careers', '공식 Career Portal', 'custom', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p2-0067-wells-fargo', 3112, 'Wells Fargo', 'https://www.wellsfargojobs.com/en/jobs/', 'https://www.wellsfargojobs.com/en/talent-community/', 'Talent Community', 'custom', 'valid_direct_talent_form', 'high', 'unknown', 'available', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p4-0451-k2-integrity', 3291, 'K2 Integrity', 'https://k2integrity.careers.hibob.com/jobs', 'https://www.k2integrity.com/en/careers/', '공식 Career Portal', 'custom', 'career_page_only', 'high', 'unknown', 'unknown', 1, '2026-08-05') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
-- The prior rows pointed at talent or corporate landing pages instead of the
-- exact first-party listings. Requeue this bounded repair set immediately;
-- source leasing still prevents duplicate concurrent crawls.
UPDATE `sources`
SET `next_crawl_at` = CURRENT_TIMESTAMP,
    `updated_at` = CURRENT_TIMESTAMP
WHERE `id` IN (
  'audit-row-342',
  'p2-0067-wells-fargo',
  'p4-0450-jfrog',
  'p4-0451-k2-integrity',
  'p5-1041-rippling'
);
