-- catalog-version: sha256:b383d22fec08860ab896679c1bd51fe03b8158cf756ce5e5feadada7d8d59de6
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p5-0755-tower-semiconductor', 2718, 'Tower Semiconductor', 'https://careers.towersemi.com/', 'https://careers.towersemi.com/subscribe-to-job-alerts/', '공식 채용공고·Job Alerts', 'custom', 'valid_posting_feed', 'high', 'unknown', 'unknown', 1, '2026-08-31') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, next_crawl_at = CASE WHEN sources.posting_url IS NOT excluded.posting_url OR sources.adapter IS NOT excluded.adapter THEN CURRENT_TIMESTAMP ELSE sources.next_crawl_at END, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-legacy-row-87', 'legacy-row-87', 'https://jobs.coreandmain.com/p/coreandmain/jobs', 'available', 'available', '2026-08-25') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-p5-0755-tower-semiconductor', 'p5-0755-tower-semiconductor', 'https://careers.towersemi.com/subscribe-to-job-alerts/', 'unknown', 'unknown', '2026-08-31') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-p4-0386-whatnot', 'p4-0386-whatnot', 'https://careers.whatnot.com/', 'unknown', 'unknown', '2026-08-31') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-p5-0522-disney', 'p5-0522-disney', 'https://www.disneycareers.com/en/', 'unknown', 'available', '2026-08-25') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
UPDATE jobs SET status = 'closed', closed_at = COALESCE(closed_at, CURRENT_TIMESTAMP), updated_at = CURRENT_TIMESTAMP WHERE status = 'open' AND source_id IN (SELECT id FROM sources WHERE enabled = 0);
UPDATE job_matches SET is_active = 0 WHERE is_active = 1 AND job_id IN (SELECT jobs.id FROM jobs JOIN sources ON sources.id = jobs.source_id WHERE sources.enabled = 0);
INSERT INTO catalog_state (key, value, updated_at) VALUES ('sources', 'v2:sha256:77c5ddcda4852fe896955c5e95a8d3cda23f644882446156053b2b41831f87b3', CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP;
DELETE FROM catalog_state WHERE key = 'sources_sync_lock_v1';
UPDATE sources SET next_crawl_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = 'p5-0755-tower-semiconductor';
PRAGMA optimize;
