-- catalog-version: sha256:133371cf18725f465ee92e77364fcd4f49e8ac4ad310f517b9356de30cdef16f
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p2-0183-webster-bank', 1290, 'Webster Bank', 'https://websteronline.wd12.myworkdayjobs.com/WebsterExternalCareerSite', 'https://websteronline.wd12.myworkdayjobs.com/en-US/WebsterExternalCareerSite/introduceYourself', '공식 Workday 채용공고/후보자 프로필', 'workday', 'valid_posting_feed', 'high', 'available', 'available', 1, '2026-09-01') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-p2-0183-webster-bank', 'p2-0183-webster-bank', 'https://websteronline.wd12.myworkdayjobs.com/en-US/WebsterExternalCareerSite/introduceYourself', 'available', 'available', '2026-09-01') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
UPDATE jobs SET status = 'closed', closed_at = COALESCE(closed_at, CURRENT_TIMESTAMP), updated_at = CURRENT_TIMESTAMP WHERE status = 'open' AND source_id IN (SELECT id FROM sources WHERE enabled = 0);
UPDATE job_matches SET is_active = 0 WHERE is_active = 1 AND job_id IN (SELECT jobs.id FROM jobs JOIN sources ON sources.id = jobs.source_id WHERE sources.enabled = 0);
INSERT INTO catalog_state (key, value, updated_at) VALUES ('sources', 'v2:sha256:835306aa88bf670a9266a8abb509471bf5ac9d7170dcabdee2ff62f70cf66e25', CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP;
DELETE FROM catalog_state WHERE key = 'sources_sync_lock_v1';
UPDATE sources SET `next_crawl_at` = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = 'p2-0183-webster-bank';
PRAGMA optimize;
