-- catalog-version: sha256:519d295d7ef22d663ad0ef23ec1ddaac23f5d188d09dcf687bf32793fbdf03c0
INSERT INTO sources (id, master_row, company, posting_url, talent_url, channel, adapter, verification, confidence, resume_upload, job_alerts, enabled, checked_at) VALUES ('p2-0183-webster-bank', 1290, 'Webster Bank', 'https://websteronline.wd12.myworkdayjobs.com/WebsterExternalCareerSite', 'https://websteronline.wd12.myworkdayjobs.com/en-US/WebsterExternalCareerSite/introduceYourself', '공식 Workday 채용공고/후보자 프로필', 'workday', 'valid_posting_feed', 'high', 'available', 'available', 1, '2026-09-01') ON CONFLICT(id) DO UPDATE SET master_row = excluded.master_row, company = excluded.company, posting_url = excluded.posting_url, talent_url = excluded.talent_url, channel = excluded.channel, adapter = excluded.adapter, verification = excluded.verification, confidence = excluded.confidence, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, enabled = excluded.enabled, checked_at = excluded.checked_at;
INSERT INTO talent_targets (id, source_id, official_url, resume_upload, job_alerts, checked_at) VALUES ('talent-p2-0183-webster-bank', 'p2-0183-webster-bank', 'https://websteronline.wd12.myworkdayjobs.com/en-US/WebsterExternalCareerSite/introduceYourself', 'available', 'available', '2026-09-01') ON CONFLICT(id) DO UPDATE SET source_id = excluded.source_id, official_url = excluded.official_url, resume_upload = excluded.resume_upload, job_alerts = excluded.job_alerts, checked_at = excluded.checked_at;
UPDATE jobs SET status = 'closed', closed_at = COALESCE(closed_at, CURRENT_TIMESTAMP), updated_at = CURRENT_TIMESTAMP WHERE status = 'open' AND source_id IN (SELECT id FROM sources WHERE enabled = 0);
UPDATE job_matches SET is_active = 0 WHERE is_active = 1 AND job_id IN (SELECT jobs.id FROM jobs JOIN sources ON sources.id = jobs.source_id WHERE sources.enabled = 0);
INSERT INTO catalog_state (key, value, updated_at) VALUES ('sources', 'v2:sha256:74fb574f9ac21f60c31256870aaf1aea0972af4914c666c986700e3c20d85bc2', CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP;
DELETE FROM catalog_state WHERE key = 'sources_sync_lock_v1';
UPDATE sources SET `next_crawl_at` = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id IN ('p2-0183-webster-bank', 'p4-0369-tigerconnect', 'audit-row-3447', 'audit-row-3448', 'p4-0285-google', 'legacy-row-84', 'audit-row-342', 'p5-0842-carefirst-bluecross-blueshield');
UPDATE jobs SET location_region = 'non_us', location_country = COALESCE(location_country, 'Germany'), updated_at = CURRENT_TIMESTAMP WHERE source_id = 'legacy-row-779' AND upper(trim(location)) LIKE '%, DE';
PRAGMA optimize;
