import type {
  ActivityEvent,
  JobPosting,
  KeywordRule,
  SourceRecord,
  TalentTarget,
} from "./domain";

export const fixtureJobs: JobPosting[] = [
  {
    id: "job-001",
    sourceId: "source-stripe",
    company: "Stripe",
    title: "Fraud Strategy Analyst",
    location: "San Francisco, CA",
    arrangement: "hybrid",
    summary: "Build fraud detection strategy and improve payment risk controls.",
    officialUrl: "https://stripe.com/jobs/search",
    matchedTerms: ["fraud", "risk"],
    matchScore: 98,
    firstSeenAt: "2026-08-08T15:20:00.000Z",
    lastConfirmedAt: "2026-08-08T17:50:00.000Z",
    status: "new",
  },
  {
    id: "job-002",
    sourceId: "source-block",
    company: "Block",
    title: "Senior Data Scientist, Fraud",
    location: "Remote, US",
    arrangement: "remote",
    summary: "Model fraud patterns across commerce and consumer products.",
    officialUrl: "https://block.xyz/careers/jobs",
    matchedTerms: ["fraud", "data scientist"],
    matchScore: 96,
    firstSeenAt: "2026-08-08T14:40:00.000Z",
    lastConfirmedAt: "2026-08-08T17:42:00.000Z",
    status: "new",
  },
  {
    id: "job-003",
    sourceId: "source-airbnb",
    company: "Airbnb",
    title: "Machine Learning Engineer, Trust",
    location: "United States",
    arrangement: "remote",
    summary: "Build machine-learning systems for platform trust and safety.",
    officialUrl: "https://careers.airbnb.com/positions/",
    matchedTerms: ["machine learning", "trust"],
    matchScore: 92,
    firstSeenAt: "2026-08-08T12:15:00.000Z",
    lastConfirmedAt: "2026-08-08T17:31:00.000Z",
    status: "saved",
  },
  {
    id: "job-004",
    sourceId: "source-coinbase",
    company: "Coinbase",
    title: "Risk Analytics Manager",
    location: "Remote, US",
    arrangement: "remote",
    summary: "Lead analytics for transaction monitoring and risk operations.",
    officialUrl: "https://www.coinbase.com/careers/positions",
    matchedTerms: ["risk", "analytics"],
    matchScore: 90,
    firstSeenAt: "2026-08-07T21:10:00.000Z",
    lastConfirmedAt: "2026-08-08T17:20:00.000Z",
    status: "new",
  },
  {
    id: "job-005",
    sourceId: "source-palantir",
    company: "Palantir",
    title: "Forward Deployed Data Scientist",
    location: "New York, NY",
    arrangement: "onsite",
    summary: "Translate operational questions into robust data workflows.",
    officialUrl: "https://www.palantir.com/careers/",
    matchedTerms: ["data scientist", "operations"],
    matchScore: 88,
    firstSeenAt: "2026-08-07T18:30:00.000Z",
    lastConfirmedAt: "2026-08-08T16:58:00.000Z",
    status: "new",
  },
  {
    id: "job-006",
    sourceId: "source-figma",
    company: "Figma",
    title: "Product Data Scientist",
    location: "San Francisco, CA",
    arrangement: "hybrid",
    summary: "Shape product decisions through experimentation and causal analysis.",
    officialUrl: "https://www.figma.com/careers/",
    matchedTerms: ["product analytics", "experimentation"],
    matchScore: 86,
    firstSeenAt: "2026-08-07T16:45:00.000Z",
    lastConfirmedAt: "2026-08-08T16:51:00.000Z",
    status: "saved",
  },
  {
    id: "job-007",
    sourceId: "source-notion",
    company: "Notion",
    title: "Analytics Engineer",
    location: "New York, NY",
    arrangement: "hybrid",
    summary: "Create trusted product and go-to-market data models.",
    officialUrl: "https://www.notion.com/careers",
    matchedTerms: ["analytics", "data models"],
    matchScore: 82,
    firstSeenAt: "2026-08-06T19:20:00.000Z",
    lastConfirmedAt: "2026-08-08T16:44:00.000Z",
    status: "new",
  },
  {
    id: "job-008",
    sourceId: "source-cloudflare",
    company: "Cloudflare",
    title: "Security Data Analyst",
    location: "Austin, TX",
    arrangement: "hybrid",
    summary: "Investigate security signals and improve detection reporting.",
    officialUrl: "https://www.cloudflare.com/careers/jobs/",
    matchedTerms: ["security", "data analyst"],
    matchScore: 79,
    firstSeenAt: "2026-08-06T14:10:00.000Z",
    lastConfirmedAt: "2026-08-08T16:31:00.000Z",
    status: "hidden",
  },
  {
    id: "job-009",
    sourceId: "source-snowflake",
    company: "Snowflake",
    title: "Applied Scientist, Search",
    location: "Bellevue, WA",
    arrangement: "onsite",
    summary: "Develop ranking and retrieval systems for enterprise data discovery.",
    officialUrl: "https://careers.snowflake.com/us/en/search-results",
    matchedTerms: ["applied scientist", "ranking"],
    matchScore: 77,
    firstSeenAt: "2026-08-05T22:00:00.000Z",
    lastConfirmedAt: "2026-08-08T16:15:00.000Z",
    status: "new",
  },
  {
    id: "job-010",
    sourceId: "source-datadog",
    company: "Datadog",
    title: "Data Engineer, Product Analytics",
    location: "Boston, MA",
    arrangement: "hybrid",
    summary: "Build reliable datasets for product measurement and reporting.",
    officialUrl: "https://careers.datadoghq.com/",
    matchedTerms: ["data engineer", "product analytics"],
    matchScore: 74,
    firstSeenAt: "2026-08-05T18:05:00.000Z",
    lastConfirmedAt: "2026-08-08T15:59:00.000Z",
    status: "applied",
  },
  {
    id: "job-011",
    sourceId: "source-atlassian",
    company: "Atlassian",
    title: "Senior Product Analyst",
    location: "Remote, US",
    arrangement: "remote",
    summary: "Guide product strategy with behavioral analysis and experiments.",
    officialUrl: "https://www.atlassian.com/company/careers/all-jobs",
    matchedTerms: ["product analyst", "experiments"],
    matchScore: 72,
    firstSeenAt: "2026-08-04T20:35:00.000Z",
    lastConfirmedAt: "2026-08-08T15:40:00.000Z",
    status: "new",
  },
  {
    id: "job-012",
    sourceId: "source-github",
    company: "GitHub",
    title: "Business Intelligence Analyst",
    location: "Remote, US",
    arrangement: "remote",
    summary: "Build decision systems and metrics for global operations.",
    officialUrl: "https://www.github.careers/careers-home/jobs",
    matchedTerms: ["business intelligence", "metrics"],
    matchScore: 70,
    firstSeenAt: "2026-08-04T16:25:00.000Z",
    lastConfirmedAt: "2026-08-08T15:22:00.000Z",
    status: "hidden",
  },
];

export const fixtureSources: SourceRecord[] = [
  { id: "source-stripe", company: "Stripe", postingUrl: "https://stripe.com/jobs/search", talentUrl: null, adapter: "custom", health: "healthy", httpStatus: 200, currentJobs: 146, lastCheckedAt: "2026-08-08T17:50:00.000Z", lastChangedAt: "2026-08-08T15:20:00.000Z", nextRunAt: "2026-08-08T23:50:00.000Z" },
  { id: "source-block", company: "Block", postingUrl: "https://block.xyz/careers/jobs", talentUrl: null, adapter: "greenhouse", health: "healthy", httpStatus: 200, currentJobs: 218, lastCheckedAt: "2026-08-08T17:42:00.000Z", lastChangedAt: "2026-08-08T14:40:00.000Z", nextRunAt: "2026-08-08T23:42:00.000Z" },
  { id: "source-airbnb", company: "Airbnb", postingUrl: "https://careers.airbnb.com/positions/", talentUrl: "https://careers.airbnb.com/talent-community/", adapter: "greenhouse", health: "changed", httpStatus: 200, currentJobs: 311, lastCheckedAt: "2026-08-08T17:31:00.000Z", lastChangedAt: "2026-08-08T17:31:00.000Z", nextRunAt: "2026-08-08T23:31:00.000Z" },
  { id: "source-coinbase", company: "Coinbase", postingUrl: "https://www.coinbase.com/careers/positions", talentUrl: null, adapter: "greenhouse", health: "healthy", httpStatus: 200, currentJobs: 192, lastCheckedAt: "2026-08-08T17:20:00.000Z", lastChangedAt: "2026-08-07T21:10:00.000Z", nextRunAt: "2026-08-08T23:20:00.000Z" },
  { id: "source-palantir", company: "Palantir", postingUrl: "https://www.palantir.com/careers/", talentUrl: null, adapter: "custom", health: "blocked", httpStatus: 403, currentJobs: 0, lastCheckedAt: "2026-08-08T16:58:00.000Z", lastChangedAt: null, nextRunAt: "2026-08-08T22:58:00.000Z" },
  { id: "source-figma", company: "Figma", postingUrl: "https://www.figma.com/careers/", talentUrl: null, adapter: "greenhouse", health: "healthy", httpStatus: 200, currentJobs: 84, lastCheckedAt: "2026-08-08T16:51:00.000Z", lastChangedAt: "2026-08-07T16:45:00.000Z", nextRunAt: "2026-08-08T22:51:00.000Z" },
  { id: "source-notion", company: "Notion", postingUrl: "https://www.notion.com/careers", talentUrl: null, adapter: "greenhouse", health: "healthy", httpStatus: 200, currentJobs: 72, lastCheckedAt: "2026-08-08T16:44:00.000Z", lastChangedAt: "2026-08-06T19:20:00.000Z", nextRunAt: "2026-08-08T22:44:00.000Z" },
  { id: "source-cloudflare", company: "Cloudflare", postingUrl: "https://www.cloudflare.com/careers/jobs/", talentUrl: null, adapter: "workday", health: "failed", httpStatus: 502, currentJobs: 0, lastCheckedAt: "2026-08-08T16:31:00.000Z", lastChangedAt: null, nextRunAt: "2026-08-08T18:31:00.000Z" },
  { id: "source-snowflake", company: "Snowflake", postingUrl: "https://careers.snowflake.com/us/en/search-results", talentUrl: "https://careers.snowflake.com/us/en/jointalentcommunity", adapter: "workday", health: "healthy", httpStatus: 200, currentJobs: 356, lastCheckedAt: "2026-08-08T16:15:00.000Z", lastChangedAt: "2026-08-05T22:00:00.000Z", nextRunAt: "2026-08-08T22:15:00.000Z" },
  { id: "source-datadog", company: "Datadog", postingUrl: "https://careers.datadoghq.com/", talentUrl: null, adapter: "greenhouse", health: "inactive", httpStatus: null, currentJobs: 0, lastCheckedAt: "2026-08-08T15:59:00.000Z", lastChangedAt: null, nextRunAt: "2026-08-09T15:59:00.000Z" },
];

export const fixtureKeywords: KeywordRule[] = [
  { id: "keyword-fraud", name: "Fraud & Risk", includeTerms: ["fraud", "risk"], excludeTerms: ["intern"], locations: ["United States", "Remote"], enabled: true, mode: "six_hour", lastSentAt: "2026-08-08T12:00:00.000Z" },
  { id: "keyword-ml", name: "Applied ML", includeTerms: ["machine learning", "applied scientist"], excludeTerms: ["manager"], locations: ["United States"], enabled: true, mode: "daily_digest", lastSentAt: "2026-08-08T15:00:00.000Z" },
  { id: "keyword-product", name: "Product Analytics", includeTerms: ["product analyst", "product data scientist"], excludeTerms: [], locations: ["Remote", "New York"], enabled: true, mode: "six_hour", lastSentAt: null },
  { id: "keyword-data", name: "Data Platform", includeTerms: ["analytics engineer", "data engineer"], excludeTerms: ["staff"], locations: [], enabled: false, mode: "daily_digest", lastSentAt: "2026-08-07T15:00:00.000Z" },
];

export const fixtureTalentTargets: TalentTarget[] = [
  { id: "talent-airbnb", company: "Airbnb", ats: "Greenhouse", talentUrl: "https://careers.airbnb.com/talent-community/", resumeUpload: "available", jobAlerts: "available", state: "ready", blocker: null, lastAttemptAt: null },
  { id: "talent-snowflake", company: "Snowflake", ats: "Workday", talentUrl: "https://careers.snowflake.com/us/en/jointalentcommunity", resumeUpload: "available", jobAlerts: "available", state: "in_progress", blocker: null, lastAttemptAt: "2026-08-08T14:05:00.000Z" },
  { id: "talent-toyota", company: "Toyota", ats: "Phenom", talentUrl: "https://careers.toyota.com/us/en/jointalentcommunity", resumeUpload: "unknown", jobAlerts: "available", state: "blocked", blocker: "CAPTCHA — user action required", lastAttemptAt: "2026-08-07T22:10:00.000Z" },
  { id: "talent-merck", company: "Merck", ats: "Workday", talentUrl: "https://jobs.merck.com/us/en/jointalentcommunity", resumeUpload: "available", jobAlerts: "available", state: "ready", blocker: null, lastAttemptAt: null },
  { id: "talent-metlife", company: "MetLife", ats: "Phenom", talentUrl: "https://jobs.metlife.com/content/Talent-Community/", resumeUpload: "unknown", jobAlerts: "available", state: "completed", blocker: null, lastAttemptAt: "2026-08-06T18:40:00.000Z" },
  { id: "talent-bms", company: "Bristol Myers Squibb", ats: "Workday", talentUrl: "https://careers.bms.com/jointalentcommunity", resumeUpload: "available", jobAlerts: "available", state: "ready", blocker: null, lastAttemptAt: null },
  { id: "talent-etsy", company: "Etsy", ats: "Greenhouse", talentUrl: "https://careers.etsy.com/global/en/jointalentcommunity", resumeUpload: "job_only", jobAlerts: "available", state: "ready", blocker: null, lastAttemptAt: null },
  { id: "talent-genentech", company: "Genentech", ats: "Workday", talentUrl: "https://careers.gene.com/us/en/jointalentcommunity", resumeUpload: "available", jobAlerts: "available", state: "blocked", blocker: "Final submission — user approval required", lastAttemptAt: "2026-08-05T19:30:00.000Z" },
];

export const fixtureActivity: ActivityEvent[] = [
  { id: "activity-001", kind: "match.created", severity: "success", summary: "Two new Fraud & Risk matches are ready to review.", occurredAt: "2026-08-08T17:51:00.000Z", technicalId: "event-match-001", details: "Matched job-001 and job-002 against keyword-fraud." },
  { id: "activity-002", kind: "source.changed", severity: "warning", summary: "Airbnb source markup changed after the latest check.", occurredAt: "2026-08-08T17:31:00.000Z", technicalId: "event-source-002", details: "Content fingerprint changed; adapter still extracted records." },
  { id: "activity-003", kind: "job.created", severity: "success", summary: "Stripe added a new matching role.", occurredAt: "2026-08-08T15:20:00.000Z", technicalId: "event-job-003", details: "Created fixture record job-001." },
  { id: "activity-004", kind: "job.created", severity: "success", summary: "Block added a new matching role.", occurredAt: "2026-08-08T14:40:00.000Z", technicalId: "event-job-004", details: "Created fixture record job-002." },
  { id: "activity-005", kind: "talent.updated", severity: "info", summary: "Snowflake assisted flow moved to In progress.", occurredAt: "2026-08-08T14:05:00.000Z", technicalId: "event-talent-005", details: "No external form was submitted." },
  { id: "activity-006", kind: "email.sent", severity: "success", summary: "Daily digest demo delivery completed.", occurredAt: "2026-08-08T12:00:00.000Z", technicalId: "event-email-006", details: "Fixture event only; no email left this preview." },
  { id: "activity-007", kind: "source.failed", severity: "error", summary: "Cloudflare source returned a temporary error.", occurredAt: "2026-08-08T10:31:00.000Z", technicalId: "event-source-007", details: "Recorded HTTP 502 and scheduled an earlier retry." },
  { id: "activity-008", kind: "job.updated", severity: "info", summary: "Coinbase role location metadata was refreshed.", occurredAt: "2026-08-07T21:10:00.000Z", technicalId: "event-job-008", details: "Arrangement remains remote." },
  { id: "activity-009", kind: "talent.updated", severity: "warning", summary: "Toyota flow is waiting for user CAPTCHA action.", occurredAt: "2026-08-07T20:10:00.000Z", technicalId: "event-talent-009", details: "Automation stopped before the restricted gate." },
  { id: "activity-010", kind: "job.closed", severity: "info", summary: "One older demo role is no longer listed.", occurredAt: "2026-08-07T16:00:00.000Z", technicalId: "event-job-010", details: "Lifecycle record retained for history." },
  { id: "activity-011", kind: "email.failed", severity: "error", summary: "One demo alert is waiting for backend configuration.", occurredAt: "2026-08-07T14:00:00.000Z", technicalId: "event-email-011", details: "No email provider is connected in this frontend slice." },
  { id: "activity-012", kind: "crawl.demo", severity: "info", summary: "Demo data · simulated crawl completed; no network request was made.", occurredAt: "2026-08-07T12:00:00.000Z", technicalId: "event-crawl-012", details: "Preview repository state only." },
];
